name: Waka Readme

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@0.1.2
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
